[tool.isort]
profile = "ruff"

[tool.ruff]
ignore = ["E501"]
line-length = 89
select = [
    "B",
    "B9",
    "C",
    "E",
    "F",
    "W",
]
target-version = "py39"

[tool.ruff.mccabe]
max-complexity = 18

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "F401",
    "F403",
]