job_contract_types = [
    "Full-time",
    "Part-time",
    "Contract",
    "Temporary",
    "Freelance",
    "Internship",
    "Apprenticeship",
    "Remote",
    "Consultant",
    "Seasonal",
    "Project-based",
    "Volunteer",
    "Per Diem",
    "Fixed-Term",
    "Zero-Hour",
    "Commission-based",
]

job_presences = ["Remote", "Hybrid", "On Site"]

job_types = [
    "Engineering",
    "Management",
    "Commercial",
    "Growth & Organisation",
    "Product",
    "Research",
    "Software Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Network Engineer",
    "Systems Administrator",
    "Database Administrator",
    "Web Developer",
    "Cybersecurity Analyst",
    "Cloud Engineer",
    "DevOps Engineer",
    "UI/UX Designer",
    "Product Manager",
    "Business Analyst",
    "IT Consultant",
    "Quantum Computing Researcher",
    "Quantum Engineer",
    "Quantum Algorithms Developer",
    "Quantum Information Scientist",
    "Quantum Hardware Engineer",
    "Quantum Software Developer",
]
