name: Ruff

on:
  push:
    paths:
      - src/**
      - .github/workflows/ruff.yml
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
